sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - axel
    - cpanminus
    - libluajit-5.1-dev

cache:
  apt: true
  directories:
  - download-cache

env:
  global:
    - JOBS=2
    - LUAJIT_PREFIX=/opt/luajit21
    - LUAJIT_LIB=$LUAJIT_PREFIX/lib
    - LUAJIT_INC=$LUAJIT_PREFIX/include/luajit-2.1
    - LUA_INCLUDE_DIR=$LUAJIT_INC
    - LUA_CMODULE_DIR=/lib
    - LD_LIBRARY_PATH=$LUAJIT_LIB:$LD_LIBRARY_PATH
    - TEST_NGINX_SLEEP=0.006
  matrix:
    - NGINX_VERSION=1.13.6

install:
    - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
    - git clone https://github.com/openresty/openresty.git ../openresty
    - git clone https://github.com/openresty/lua-nginx-module.git ../lua-nginx-module
    - git clone https://github.com/openresty/nginx-devel-utils.git
    - git clone -b v2.1-agentzh https://github.com/openresty/luajit2.git
    - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx

script:
  # compile luajit
  - cd luajit2/
  - make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC
      XCFLAGS='-DLUA_USE_APICHECK -DLUA_USE_ASSERT -msse4.2' > build.log 2>&1
      || (cat build.log && exit 1)
  - sudo make install PREFIX=$LUAJIT_PREFIX > build.log 2>&1 ||
      (cat build.log && exit 1)
  - cd ..
  - export PATH=$PWD/work/nginx/sbin:$PWD/nginx-devel-utils:$PATH
  - ngx-build $NGINX_VERSION --with-debug --with-cc-opt="-DDEBUG_MALLOC"
      --with-ipv6 --add-module=../lua-nginx-module  > build.log 2>&1 ||
      (cat build.log && exit 1)
  - prove -r t
